# Generated by Django 3.2.7 on 2021-09-23 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.UUIDField()),
                ('last_to_play', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_peak', models.IntegerField()),
                ('left_peak', models.IntegerField()),
                ('if_full', models.BooleanField()),
                ('y', models.IntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playdot.board')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('value', models.CharField(max_length=1)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playdot.board')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playdot.row')),
            ],
        ),
    ]
