# Generated by Django 3.2.7 on 2021-09-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playdot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='last_to_play',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='row',
            name='if_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='row',
            name='left_peak',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='row',
            name='right_peak',
            field=models.IntegerField(null=True),
        ),
    ]
