# Generated by Django 3.2.7 on 2021-09-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playdot', '0002_auto_20210923_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='width',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
