# Generated by Django 3.2.7 on 2021-09-23 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playdot', '0003_board_width'),
    ]

    operations = [
        migrations.RenameField(
            model_name='row',
            old_name='if_full',
            new_name='is_full',
        ),
    ]
