# Generated by Django 3.2.7 on 2021-09-26 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playdot', '0006_playdotgamedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamedata',
            old_name='metadata',
            new_name='meta',
        ),
    ]
