# Generated by Django 3.2.7 on 2021-09-28 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playdot', '0010_auto_20210927_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_winning_in', to='playdot.piece'),
        ),
    ]
