# Generated by Django 3.2.7 on 2021-09-28 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playdot', '0011_gamedata_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='is_full',
        ),
        migrations.RemoveField(
            model_name='row',
            name='left_peak',
        ),
        migrations.RemoveField(
            model_name='row',
            name='right_peak',
        ),
    ]
