# Generated by Django 3.2.7 on 2021-09-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playdot', '0012_auto_20210928_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelplayer',
            name='playing_as',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='next_to_play',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='winner',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Piece',
        ),
    ]
