# Generated by Django 3.2.7 on 2021-10-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playdot', '0013_auto_20210929_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='is_single_player',
            field=models.BooleanField(default=False),
        ),
    ]
